app_launch_prefix = "uwsm app -- "
force_keyboard_focuse = true
selection_wrap = true
hide_action_hints = true

[placeholders]
"default" = { input = "ï€‚ Search...", list = "No Results" }

[keybinds]
quick_activate = []

[columns]
symbols = 1

[providers]
max_results = 256
default = ["desktopapplications", "websearch"]

[[providers.prefixes]]
prefix = "/"
provider = "providerlist"

[[provider.prefixes]]
prefix = "."
providers = "files"

[[providers.prefixes]]
prefix = ":"
provider = "symbols"

[[providers.prefixes]]
prefix = "="
provider = "calc"

[[providers.prefixes]]
prefix = "@"
provider = "websearch"

[[providers.prefixes]]
prefix = "$"
provider = "clipboard"
