[editor]
color-modes = true
end-of-line-diagnostics = "hint"
line-number = "relative"
mouse = false

[editor.indent-guides]
rainbow-option = "normal"

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "·"

[keys.normal.space]
"tab" = ":toggle indent-guides.render"
"space" = ":toggle whitespace.render all none"
